### PR TITLE
grape-entity 0.5 compatibility

### LINKED ISSUE #37: Support grape entity 0.5
grape entity changed the way they expose their documented attributes. The ```.exposures``` method is no longer available and its replacement ```.root_exposures``` seems to have a different signature.

### PR DESCRIPTION
**Pull request by oliverzeyen**
Update to meet the new grape-entity 0.5 signature. Splits up the whole logic into multiple classes. I will refactor some of this later on but for now this should do the trick.

Fixes #37 and a bug introduced in #39

### CODE REVIEW

**Comment by rngtng** [comment]
nice! :+1:

**Comment by rngtng** [comment]
Fixes https://github.com/Gild/ruby-swagger/issues/37

**Comment by oliverzeyen** [comment]
@rngtng Exactly! Forgot to mention!

File: lib/ruby-swagger/grape/method.rb [hunk 1]
```diff
@@ -251,7 +251,7 @@ def documented_paramter(schema, name, parameter)
     def required_parameter(schema, name, parameter)
       return if parameter.nil? || parameter[:required].nil? || parameter[:required] == false
 
-      schema['required'] ||= []
+      schema['required'] = [] unless schema['required'].is_a?(Array)
```
Comment (oliverzeyen) [inline lib/ruby-swagger/grape/method.rb]: Sorry, but this one here sneaked in. Changes in #39 cause a `NoMethodError: undefined method '<<' for true:TrueClass` on required nested exposures. Since `required? flags for regular exposures are boolean, nesting exposures collect required parameters of the object in an array called `required`. So we have to ensure we're dealing with an array.

**Comment by taganaka** [comment]
@oliverzeyen This is a very good stuff!
Thank you so much for your help.

There are some rubocop warnings, do you mind to fix the warnings so that I can merge it?

Thanks!

**Comment by oliverzeyen** [comment]
Done! :+1:

**Comment by taganaka** [comment]
nice!

**Comment by oliverzeyen** [comment]
Top! Thanks for merging!
